server:
  port: 9003
spring:
  application:
    name: hospital-service-2

  datasource:
    url: jdbc:mysql://localhost:3306/codejavadb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update