server:
  port: 9001
hospital:
  id: "1"
  name: "Mera-hospital"
hospital-manager:
  port: "9005"
spring:
  application:
    name: hospital-service
#  profiles:
#    active: 1

  datasource:
    url: jdbc:mysql://localhost:3306/dbdoctor
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update