server:
  port: 9006
hospital:
  id: "2"
  name: "Mera-dusra-hospital"
hospital-manager:
  port: "9001"
spring:
  application:
    name: hospital-service

  datasource:
    url: jdbc:mysql://localhost:3306/hospital_one
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    enabled: false